# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Notes to my future self
email: ryan DOT delaney AT gmail DOT com
description: > # this means to ignore newlines until "baseurl:"
  I'll store descriptions of how I solved problems so I can hopefully learn
  from them later
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rpdelaney.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  rpdelaney

# Build settings
markdown: kramdown
